admin_job_location:
  path: /
  defaults: {_controller: ProjectBundle:AdminJobLocation:index}
  methods:  [GET]

admin_job_location_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminJobLocation:new}
  methods:  [GET,POST]

admin_job_location_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminJobLocation:edit}
  methods:  [GET,POST]
  requirements:
    id: \d+

admin_job_location_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminJobLocation:delete}
  methods:  [GET]
  requirements:
    id: \d+

admin_job_location_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminJobLocation:group_delete}
  methods:  [POST]

admin_job_location_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminJobLocation:sort}
  methods:  [GET]

admin_job_location_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminJobLocation:sort_prosess}
  methods:  [POST]
