admin_our_brand:
  path: /
  defaults: {_controller: ProjectBundle:AdminOurBrand:index}
  requirements:
    _method: get

admin_our_brand_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminOurBrand:new}

admin_our_brand_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminOurBrand:create}
  requirements:
    _method: post

admin_our_brand_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminOurBrand:edit}
  requirements:
    id: \d+

admin_our_brand_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminOurBrand:update}
  requirements:
    _method: post
    id: \d+

admin_our_brand_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminOurBrand:delete}
  requirements:
    _method: get

admin_our_brand_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminOurBrand:group_delete}
  requirements:
    _method: post

admin_our_brand_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminOurBrand:group_enable}
  requirements:
    _method: post

admin_our_brand_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminOurBrand:group_disable}
  requirements:
    _method: post

admin_our_brand_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminOurBrand:sort}
  requirements:
    _method: get

admin_our_brand_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminOurBrand:sort_prosess}
  requirements:
    _method: post
