<?php

namespace ProjectBundle\Repository;

/**
 * ApplyJobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplyJobsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllData($arr_query_data=false)
	{
			//QueryBuilder Expr
			$qb = $this->createQueryBuilder('aj');
			$qb->orderBy('aj.createdAt', 'DESC');

			if(isset($arr_query_data['q'])){
				$q = $arr_query_data['q'];
				$qb->where($qb->expr()->orX(
					$qb->expr()->like('aj.firstName', ':query'),
					$qb->expr()->like('aj.lastName', ':query'),
					$qb->expr()->like('aj.email', ':query'),
					$qb->expr()->like('aj.message', ':query')
				))
				->setParameter('query', '%'.$q.'%');
			}
			return $qb;
	}

	public function countBy(array $criteria)
  {
      $persister = $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName);
      return $persister->count($criteria);
  }
}
