<?php

namespace ProjectBundle\Repository;

/**
 * AttachFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachFileRepository extends \Doctrine\ORM\EntityRepository
{
}
