<?php

namespace ProjectBundle\Repository;

/**
 * ComputerSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
