<?php

namespace ProjectBundle\Repository;

/**
 * EducationalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationalRepository extends \Doctrine\ORM\EntityRepository
{
}
