<?php

namespace ProjectBundle\Repository;

/**
 * JobLocationTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobLocationTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
