<?php

namespace ProjectBundle\Repository;

/**
 * LanguageSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
