<?php

namespace ProjectBundle\Repository;

/**
 * OtherSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
