<?php

namespace ProjectBundle\Repository;

/**
 * OurBrandVideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurBrandVideosRepository extends \Doctrine\ORM\EntityRepository
{
}
