<?php

namespace ProjectBundle\Repository;

/**
 * OurBrandTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurBrandTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
